---
- name: 'Add epel repository'
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: "{{ haproxy_repo }}/$releasever/$basearch/

- name: Install HAProxy (yum)
  yum:
    name: "{{ haproxy_package_name }}"
