---
- name: 'Check epel repo'
  shell: yum repolist | grep -qi EPEL
  register: epel_repo_check
  check_mode: false

- name: 'Add epel repo'
  template:
    src: "epel.repo"
    dest: "/etc/yum.repos.d/epel.repo"
    owner: "root"
    group: "root"
    mode: "0644"
  when: epel_repo_check is defined and epel_repo_check.rc != 0

- name: Install HAProxy (yum)
  yum:
    name: "{{ haproxy_package_name }}"
