---
- name: Add haproxy apt repo (jessie)
  apt_repository:
    repo: "deb http://http.debian.net/debian {{ ansible_distribution_release }} main"
    state: present
    update_cache: yes
  when: ansible_distribution_release == 'jessie'

- name: Install HAProxy (jessie)
  apt:
    name: "{{ haproxy_package_name }}"
    default_release: "{{ ansible_distribution_release }}"
  when: ansible_distribution_release == 'jessie'
